name: Deploy Application Action
description: Marks application as deployed with specified url
branding:
  icon: server
  color: purple
inputs:
  deploymentId:
    description: Deployment id when setting only status
    required: false
  state:
    description: Status of deployment
    required: false
    default: pending
  environmentUrl:
    description: Environment url to link to
    required: false
  requiredContext:
    description: Environment url to link to
    required: false
    default: ''
  autoMerge:
    description: Auto merge
    required: false
    default: 'false'
  environment:
    description: Transient environment
    required: false
    default: 'qa'
  transientEnvironment:
    description: Transient environment
    required: false
    default: 'true'
  productionEnvironment:
    description: Production environment
    required: false
    default: 'false'
  # onStateFailureStopBuild:
  #   description: Github token
  #   required: false
  #   default: 'true'
  token:
    description: Github token
    required: true

outputs:
  deploymentId: # id of the output
    description: 'The sum of the inputs'
runs:
  using: 'node12'
  main: 'dist/index.js'
