name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
          yarn all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: deployment
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          environmentUrl: https://github.com/features/actions
      - uses: ./
        with:
          deploymentId: ${{steps.deployment.outputs.deploymentId}}
          token: ${{secrets.GITHUB_TOKEN}}
          environmentUrl: https://github.com/features/actions
          state: success
